# Generated by Django 3.1.4 on 2020-12-02 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrar',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('registrar_s_num', models.AutoField(primary_key=True, serialize=False)),
                ('registrar_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('registrar_username', models.CharField(max_length=20, unique=True)),
                ('registrar_fname', models.CharField(max_length=50)),
                ('registrar_lname', models.CharField(max_length=50)),
                ('registrar_email', models.EmailField(default='email@email.com', max_length=200, unique=True)),
                ('registrar_phone', models.IntegerField(blank=True, null=True)),
                ('registrar_type', models.CharField(choices=[('V', 'Vendor'), ('B', 'Bidder')], max_length=1)),
                ('registrar_superuser', models.BooleanField(default=False)),
                ('registrar_active', models.BooleanField(default=True)),
                ('registrar_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Account_users',
            },
        ),
    ]
